### ISSUE TITLE
No attributes presented

### ISSUE THREAD

**Issue by liedekef** [simplesamlphp/simplesamlphp-module-consent#18]
Whe accessing simplesamlphp as an IDP like this:
http://localhost/simplesaml/saml2/idp/SSOService.php?spentityid=https://my.entity.id

the consent module doesn't list the attributes being sent. The array $state['Attributes'] (as used in www/getconsent.php) is empty, while the relevant SP config in saml20-sp-remote.php contains this definition:
```
  'attributes' =>
  array (
    0 => 'urn:oid:1.3.6.1.4.1.5923.1.1.1.6',
    1 => 'urn:oid:0.9.2342.19200300.100.1.3',
    2 => 'urn:oid:2.5.4.3',
  ),
  'attributes.required' =>
  array (
    0 => 'urn:oid:1.3.6.1.4.1.5923.1.1.1.6',
    1 => 'urn:oid:0.9.2342.19200300.100.1.3',
    2 => 'urn:oid:2.5.4.3',
  ),
```

In config.php I have this in the section authproc.idp: 
```
    'authproc.idp' => [
        10 => [
            'class' => 'simpletotp:2fa',
            'secret_attr' => 'totp_attr',
            'enforce_2fa' => false,
            'not_configured_url' => '',
        ],
        30 => 'core:LanguageAdaptor',
        45 => [
            'class'         => 'core:StatisticsWithAttribute',
            'attributename' => 'realm',
            'type'          => 'saml20-idp-SSO',
        ],
        50 => 'core:AttributeLimit',
        90 => [
            'class' => 'consent:Consent',
            'identifyingAttribute' => 'eduPersonPrincipalName',
            'store' => 'consent:Cookie',
            'focus' => 'yes',
            'checked' => true
        ],
        98 => [
                'class' => 'core:AttributeAlter',
                'subject' => 'totp_attr',
                'pattern' => '/.*/',
                '%remove',
        ],
        99 => 'core:LanguageAdaptor',
```
Changing anything in the 50-definition doesn't impact the result at all, the list of shown attributes stay empty ...

**Comment by ghalse** [comment]
I don't think your identifyingAttribute exists in that config. Your incoming request has urn:oid:1.3.6.1.4.1.5923.1.1.1.6 but you are using eduPersonPrincipalName. I suspect you either need to run your attributes through `core:AttributeMap` or you need to change your identifyingAttribute to urn:oid:1.3.6.1.4.1.5923.1.1.1.6

**Comment by liedekef** [comment]
Sorry, meanwhile I played around and fixed the issues at hand, so I'll close this.
