### ISSUE TITLE
"consent.css" not found on SSP v2.0.0 due the old "www" dir

### ISSUE THREAD

**Issue by malavolti** [simplesamlphp/simplesamlphp-module-consent#21]
Dear @tvdijen,

can I ask if a new version of simplesamlphp-module-consent can be release to solve the follwing issue reported by SSP v2.0.0 log?

```bash
Mar  2 15:37:00 ssp-idp simplesamlphp[41334]: 6 [99ec8e59fc] Could not find file '/var/simplesamlphp/vendor/simplesamlphp/simplesamlphp/modules/consent/public/assets/css/consent.css'.
```
it is cause by the name of the "**www**" dir provided by the module.

Thank you so much!
Marco

**Comment by tvdijen** [comment]
Tagged v1.2.2 !
Sorry you are experiencing these issues.. I was under the impression that we had tagged working releases for every module.
