### ISSUE TITLE
Warning on consent-form

### ISSUE THREAD

**Issue by tvdijen** [simplesamlphp/simplesamlphp-module-consent#7]
I was just testing with the latest release when I ran into a warning:

Notice: Undefined index: UIInfo in /apps/installation/simplesamlphp/simplesamlphp-master/modules/consent/www/getconsent.php on line 163 Warning: array_key_exists() expects parameter 2 to be array, null given in /apps/installation/simplesamlphp/simplesamlphp-master/modules/consent/www/getconsent.php on line 163 Notice: Undefined index: UIInfo in /apps/installation/simplesamlphp/simplesamlphp-master/modules/consent/www/getconsent.php on line 167 Warning: array_key_exists() expects parameter 2 to be array, null given in /apps/installation/simplesamlphp/simplesamlphp-master/modules/consent/www/getconsent.php on line 167 

Now, I haven't really looked into it yet, but since UIInfo is an optional field in SAML metadata, we should probably add another check to see if it exists in the first place.

@nordlolek ! Could you perhaps have another look at this? You would really help us out!

**Comment by nordlolek** [comment]
hi! shure. i will look into it.

**Comment by tvdijen** [comment]
Closed in #8
